name: Update IP List

on: 
  push:
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests lxml
      - name: Run Python
        run: |
          python scripts/ChinaIP.py
          python scripts/cn.py
          python scripts/ChinaIP6.py
          python scripts/cn6.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update IP List
